### ISSUE TITLE
java.lang.NullPointerException: inventory must not be null

### ISSUE THREAD

**Issue by DocAndrei** [Cynosphere-mc/Scout#27] opened 2022-12-10 12:46 UTC
Game crashes when I open my inventory. Other stuff like moving, opening chests, crafting seems to work.
I think there is an incompatibilty with another mod/library (the modpack runs without the scout.jar)
I am asking if the issue is already known and if there s any workaorund.

the Crash Report 
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2022-12-10 14:33:17
Description: Rendering screen

java.lang.NullPointerException: inventory must not be null
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.getSlotLocations(Unknown Source)
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.drawSprite(Unknown Source)
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.onBackgroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
	at net.minecraft.class_465.handler$bhf000$onBackgroundRender(class_465.java)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.getSlotLocations(Unknown Source)
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.drawSprite(Unknown Source)
	at org.anti_ad.mc.ipnext.event.LockSlotsHandler.onBackgroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
	at net.minecraft.class_465.handler$bhf000$onBackgroundRender(class_465.java)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (213, 133). Absolute: (1280.000000, 800.000000)
	Screen size: Scaled: (427, 267). Absolute: (2560, 1600). Scale factor of 6.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['-'/164, l='ClientLevel', x=-23.46, y=63.00, z=-13.07]]
	Chunk stats: 4096, 1830
	Level dimension: minecraft:overworld
	Level spawn location: World: (6,127,6), Section: (at 6,15,6 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 483940 game time, 523308 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_r620044.zip, black_icons

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.5, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2536903328 bytes (2419 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24dd
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1236
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29036.06
	Virtual memory used (MB): 22450.80
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 258.43
	JVM Flags: 24 total; -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:ParallelGCThreads=16 -XX:ShenandoahGCHeuristics=static -XX:+UseLargePages -XX:+UseLargePagesIndividualAllocation -XX:+AlwaysPreTouch -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+OptoScheduling -XX:+OptoBundling -XX:+UseStringDeduplication -XX:+AllowParallelDefineClass -XX:+UseVectorCmov -XX:-DontCompileHugeMethods -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M

	Fabric Mods: 
		appleskin: AppleSkin 2.4.1+mc1.19
		betterf3: BetterF3 4.0.0
		carpet: Carpet Mod 1.4.84
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 5.16
			fiber: fiber 0.23.0-2
		easiervillagertrading: EasierVillagerTrading 1.19.1-fabric0.58.5-1.5.4
			gbfabrictools: GBfabrictools 1.3.4+1.19
		editsign: EditSign 2.6.0
		enchantedshulkers: Enchanted Shulkers 1.0.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			mm: Manningham Mills 2.3
		fabric-api: Fabric API 0.67.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.37+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.1+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.30+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.7+9244241690
			fabric-networking-v0: Fabric Networking (v0) 0.3.24+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.28+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.14+12bfe4ea90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.16+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.3+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		ferritecore: FerriteCore 5.0.3
		inventoryprofilesnext: Inventory Profiles Next 1.8.5
		inventorytabs: Inventory Tabs 0.8.1-1.19.x
		inventorytotem-fabric: Inventory Totem (Fabric) 2.1
		itemscroller: Item Scroller 0.17.1
		itemswapper: ItemSwapper 0.3.2-mc1.19.2
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.4.0.286
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 1.0.6
		litematica: Litematica 0.12.5
		lithium: Lithium 0.10.2
		malilib: MaLiLib 0.13.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.1.1
		mousetweaks: Mouse Tweaks 2.22
		quickshulker: Quick Shulker 1.3.9-1.19
			kyrptconfig: Kyrpt Config 1.4.16-1.19
			shulkerutils: shulkerutils 1.0.4-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		scout: Scout 1.1.1
		shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
		shulkerpick: ShulkerPick 1.0.0-1.18
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.13+mc1.19.2-build.76
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		stacker: Stacker 3.0.2-1.19.x
			stacc: Stacc 1.3.4
		starlight: Starlight 1.1.1+fabric.ae22326
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		trinkets: Trinkets 3.4.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		tweakeroo: Tweakeroo 0.14.3
		voicechat: Simple Voice Chat 1.19.2-2.3.16
		whereisit: Where Is It 1.14.13
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		xaerominimap: Xaero's Minimap 22.16.2
		xaeroworldmap: Xaero's World Map 1.28.3
	Launched Version: fabric-loader-0.14.10-1.19.2

	Data Packs: vanilla, Fabric Mods, file/afk display v1.1.3.zip, file/anti enderman grief v1.1.3.zip, file/armor statues v2.8.4.zip, file/armored elytra v1.0.6.zip, file/dragon drops v1.3.3.zip, file/fast leaf decay v2.0.6.zip, file/more mob heads v2.10.1.zip, file/player head drops v1.1.3.zip, file/silence mobs v1.1.3.zip, file/thunder shrine v1.1.3.zip, file/VanillaTweaks_c315448.zip
	World Generation: Stable

**Comment by Cynosphere** [comment] 2022-12-11 04:43
Duplicate of #24

**Closed by Cynosphere** 2022-12-11 04:43 UTC
